### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by danimesq** [haskellcamargo/skype-unofficial-client#31] opened 2016-01-27 22:08 UTC
Please, give support for us test it on Windows.
Apply the needed APIs and codes on make-file.

**Comment by gizmocodes** [comment] 2016-03-06 20:12
This is a duplicate of an already solved issue https://github.com/haskellcamargo/skype-unofficial-client/issues/15.

**Closed as completed** 2016-03-27 17:08 UTC
